### ISSUE TITLE
Dynamic Connection String

### ISSUE THREAD

**Issue by ainwood** [ls612/CFCGen#1]
The datasource is hard-coded.  It can be accessed and updated using this:

`string SelectedSource = BrowseForFile();

```
        var originalConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["GameplayEntities"].ConnectionString;
        var ecsBuilder = new EntityConnectionStringBuilder(originalConnectionString);
        var sqlCsBuilder = new SqlConnectionStringBuilder(ecsBuilder.ProviderConnectionString)
        {
            DataSource = SelectedSource
        };
        var providerConnectionString = sqlCsBuilder.ToString();
        ecsBuilder.ProviderConnectionString = providerConnectionString;
```

`

...But not entirely clear how the revised string can be passed through to the EDX.

BTW:  my email is cfcgotm  < at > g m a i l . c o m for easier discussions (forums are blocked for me at work).

**Comment by ls612** [comment]
It appears there is a simpler solution: http://stackoverflow.com/questions/22101150/sqlite-ef6-programmatically-set-connection-string-at-runtime

**Comment by ainwood** [comment]
Didn't quite work, but managed to adapt it so that it does:

`public GameplayEntities(string connectionString)
    : base(new EntityConnection() { ConnectionString = connectionString }, true)
        {
        }`
