### ISSUE TITLE
Convert to base class?

### ISSUE THREAD

**Issue by ainwood** [ls612/CFCGen#2]
As per my email, I was thinking that modifying the data classes might ultimately be easier.  If we could make them inherit from another class (eg civ_base), then we could add some basic html rendering methods to that class, and it would make things a bit easier.  Eg. a method for 'parent_url' that returns the html from the class name, and another for  "Anchor" that simply returns an html string for an appropriate anchor based on the parent_url.

It would be pretty easy to manually add in the inheritance, but it will be broken if you do a database refresh (by the way - I did extend the GamePlayEntities parent class, and did that in a separate file so that it doesn't get over-written).

1.) Is it possible to regenerate the classes as inheriting from something else?
2.) Is a database refresh likely?

**Comment by ainwood** [comment]
Hey - this is something cool I didn't know about partial classes:  I added another partial class with an inheritance declaration, didn't add it to the original partial class, and the compiler is quite happy, and you can work with the class.  So we can achieve this without having to modify the base classes.  

I'll upload a starter for the base class and an extension to the 'building' class.

**Comment by ls612** [comment]
In response to your top two questions;
1. I don't think that is possible, the purpose of EF is to make sure your in-memory constructs are compatible with the underlying database, and changing the class definitions would break that guarantee.
2. Regenerating the database is highly likely, as all Firaxis would need to do is make a schema change.

**Comment by ainwood** [comment]
OK - as noted, I can achieve this by adding the inheritance to the partial class.
