### ISSUE TITLE
Derived properties

### ISSUE THREAD

**Issue by ainwood** [ls612/CFCGen#3]
I note that the classes have some derived collections of he appropriate class type.  Eg. I note that for 'buildings', the PrereqTech is included as both:

 public string PrereqTech { get; set; }
 public virtual Technology Technology { get; set; }
 
Not being familiar with the way these classes were auto generated, were these linkages developed by you, or automatically from the schema?

The reason I ask is that not all links are there.  Eg. For buildings, the ObsoleteEra is only included as a string, with no corresponding Era class instance.

I want to know whether this is something that is best fixed by checking the entity framework import, or whether I should add a method for getting these mappings (I'm not sure of the best way to do it...generics?).

**Comment by ls612** [comment]
I think the prereqtech row is the string representation of the tech the display and the Technology object is the actual reference to the technology. Unfortunately, the SDK hasn't been released so some of this is guesswork. For the Obsolete era, it appears that Firaxis simply doesn't use the reference to the Era table as a foreign key in the database but does a string comparison to the name in some instances which is incredibly bad if true. If you want to do string comparisons to figure out the references (thankfully Firaxis made the name the key for most tables) that is fine, or just printing the string literal for the era is also OK.

**Comment by ainwood** [comment]
Hmm.  OK - thanks.  The beauty of the linked class is that each is an instance of "CivBase", which means that I can just call (for example) wonder.Technology.html_Goto_URL_Link in the html generation class, and this generates a string "<a href=www.civfanatics.com\ReferenceCenter\Civ6\Technology\#ASTROLOGY>Astrology</a>"

I can't do this with plain strings without trying to do something clever to get the class instance from the name.  For the ERA, it probably doesn't matter if we can't generate a hyperlink (I see very little value in a reference page for "ERA", as the ERAs table has no information that is much use for reference).  However, it still leaves the slight problem of turning the string into something a bit more friendly:  LOC_ERA_ANCIENT_NAME into "Ancient"?

I'll stick a workaround in.
